#!/usr/bin/env bash

Help()
{
    echo "cowponder generates an ASCII art picture of a cow thinking some"
    echo "fascinating random thoughts. It word-wraps the message at about 40"
    echo "columns, and prints the cow saying the given message on standard"
    echo "output."
    echo ""
    echo "cowponder also includes ponder, which provides the same functionality"
    echo "but without the bovine centerpiece so users may pipe the thoughts to"
    echo "their contemplative creature of choice."
    echo ""
    echo "Different modes can be enabled by passing the appropriate option."
    echo "For instance -d will enable Dead mode, were the cow shown appears"
    echo "to be dead. The complete list of options are:"
    echo ""
    echo "  Borg     -b"
    echo "  Dead     -d"
    echo "  Greedy   -g"
    echo "  Paranoid -p"
    echo "  Stoned   -s"
    echo "  Youthful -y"
    echo ""
    echo "Outside of the cow modes, there are several additional options. "
    echo "Note that these are not available for ponder, since the ponder"
    echo "is the same software as cowponder and shares a thoughtbook."
    echo "  --version, -v         Display the version of cowponder and exit."
    echo "  --update,  -u         Update the thoughtbook from the interwebs."
    echo "                        This *will* erase any changes you've made; "
    echo "                        back up anything you want to keep!"
    echo "  --add, -a [thought]   Add [thought] to the thoughtbook."
}

while getopts ":h" option; do
   case $option in
      h) # display Help
         Help
         exit;;
   esac
done

cowthink $(ponder "$@")
