#!/usr/bin/python3

import argparse
import subprocess
import os
from random import SystemRandom
from os import path, popen
cowthoughts_path = path.join(popen("brew --prefix").read().strip(), "etc", "cowthoughts.txt")

random = SystemRandom() # more random

cowthoughts_file = os.path.join(os.popen("brew --prefix").read().strip(), "etc", "cowthoughts.txt")

ap = argparse.ArgumentParser(prog="ponder", description="provides the functionality of `cowponder` minus the bovine centerpiece, allowing users to pipe the output to their contemplative creature of choice.")
ap.add_argument("-v", "--version", action='store_true', help="Print version information and exit.")
ap.add_argument("-u", "--update",  action='store_true', help="Update thoughtbook from the server. This *will* overwrite any changes made with cowponder --add.")
ap.add_argument("-a", "--add", help="Add custom thought to thoughtbook.")
args = vars(ap.parse_args())

if args['version']:
	print("cowponder version 0.0.1")
	exit()
if args['update']:
	subprocess.run(["wget", "-q", "-O", cowthoughts_path, "https://max.xz.ax/cowponder/cowthoughts.txt"])
	print("updated thoughtbook (moo)")
	exit()
if thought := args['add']:
	with open(cowthoughts_path, "a") as f:
		print(thought, file=f)
	print('"', thought, '" added to thoughtbook (moo)', sep='')
	exit()


with open(cowthoughts_path) as thinkbook:
	thoughts = [thought for thought in thinkbook.read().split("\n") if thought]

thought = random.choice(thoughts)
print(thought)
