#!/usr/bin/python3

import argparse
import requests
import subprocess
import os
from random import SystemRandom
from os import path, popen
cowthoughts_path = path.join(popen("brew --prefix").read().strip(), "etc", "cowthoughts.txt")

random = SystemRandom() # more random

cowthoughts_file = os.path.join(os.popen("brew --prefix").read().strip(), "etc", "cowthoughts.txt")

ap = argparse.ArgumentParser(prog="ponder", description="provides the functionality of `cowponder` minus the bovine centerpiece, allowing users to pipe the output to their contemplative creature of choice.")
ap.add_argument("-v", "--version", action='store_true', help="Print version information and exit.")
ap.add_argument("-u", "--update",  action='store_true', help="Update thoughtbook from the server. This *will* overwrite any changes made with cowponder --add.")
ap.add_argument("-a", "--add", help="Add custom thought to thoughtbook.")
args = vars(ap.parse_args())

if args['version']:
        subprocess.run(["brew", "info", "cowponder"])
        exit()

if args['update']:
        try:
                response = requests.get('https://max.xz.ax/cowponder/cowthoughts.txt')
                if response.status_code == 200:
                        with open(cowthoughts_path, 'w') as f:
                                f.write(response.text)
                        print("updated thoughtbook (moo)")
                        exit()
                else:
                        print("failed to download cowthoughts.txt")
                        print("no changes written to local cowthoughts file")
                        exit()
        except Exception as e:
                print(f"Error while downloading cowthoughts.txt: {e}")
                exit()

with open(cowthoughts_path) as thinkbook:
	thoughts = [thought for thought in thinkbook.read().split("\n") if thought]

thought = random.choice(thoughts)
print(thought)
